### ISSUE TITLE
Feature request : Dark Themed Gists

### ISSUE THREAD

**Issue by lenicyl** [linjunpop/obsidian-gist#2]
I use dark mode everywhere including github and obsidian, however when i used this plugin i noticed that it only shows the gist in light theme, 
![image](https://user-images.githubusercontent.com/73347143/133959093-212856e0-039d-45cd-9fa5-119830905e8e.png)
Light themed gist looks odd while using a dark theme

**Comment by linjunpop** [comment]
Looks like GitHub does not provide a dark variant officially.

Maybe I can add a setting to allow the Gist theme to be overridden.

**Comment by linjunpop** [comment]
Please check 0.8.0: https://github.com/linjunpop/obsidian-gist/releases/tag/0.8.0
