### ISSUE TITLE
Feature request: Disable frontmatter inclusion

### ISSUE THREAD

**Issue by masonc15** [linjunpop/obsidian-gist#5]
Hello,

I love this addon, but don't have a need for the big block of gist-related frontmatter that appears when using it.  If there could be an option to disable that, that would be incredible.  Thank you!

**Comment by linjunpop** [comment]
Hi @masonc15 ,

Thank you. 🍻 

Do you mean the banner shows "hosted with ❤️ by GitHub"?


<img width="407" alt="image" src="https://user-images.githubusercontent.com/214616/178087826-1b9b7e9f-3eaa-4e4a-9798-26f189fedc96.png">

**Comment by masonc15** [comment]
No, I don't mean that banner.

I'm referring to within Obsidian itself as you can see in the below screenshot:
![screenshot](https://i.imgur.com/LcTpD8p.png)

Thanks!

**Comment by linjunpop** [comment]
Hi @masonc15 ,

Would you please elaborate more on "but don't have a need for the big block of gist-related frontmatter that appears when using it"?

`obsidian-gist` won't inject anything into the frontmatter and it won't render the data in frontmatter too:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/214616/178639559-3a5d3e1c-e36d-4fe2-b41c-6d71588497a5.png">

**Comment by masonc15** [comment]
Yes, I am referring to the frontmatter on the **left** side of your screenshot, in edit mode.  I'm not referring to Reading mode, where the frontmatter is not visible as you mentioned.  I don't use frontmatter at all so I don't want it to be generated every time.  Let me know if this is clear.  Thanks!

**Comment by linjunpop** [comment]
Hi @masonc15 ,

Currently `obsidian-gist` don't generate such content in the file's front matter, would you please check if you have other plugin installed which generate this?

**Comment by masonc15** [comment]
I got my addons confused.  Disregard this issue, apologies for the confusion!

**Comment by linjunpop** [comment]
🆗
