### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by TheOnlyWayUp** [linjunpop/obsidian-gist#6]

**Comment by linjunpop** [comment]
There's no official dark theme for Gist. You can customize the styles in the settings: 
<img width="1089" alt="image" src="https://github.com/linjunpop/obsidian-gist/assets/214616/1dd96936-f580-4007-b111-57cb605f2051">

A dark theme you might need is here: https://gist.github.com/adimancv/eb2f4b46d3c95e6b8fe4dd523752366.

**Comment by TheOnlyWayUp** [comment]
Hey @linjunpop, could you share the stylesheet again?

**Comment by linjunpop** [comment]
Hi @TheOnlyWayUp, you can do a Google search (https://www.google.com/search?q=gist+dark+theme), there should be several dark themes for Gist
