### ISSUE TITLE
gives error on my gists

### ISSUE THREAD

**Issue by luislopes-outsystems** [linjunpop/obsidian-gist#7]
Hi, when I try to include my gists I always get 404 errors, looking at the console, I can see it is trying to access to wrong url

my username includes a - character
luislopes-outsystems, but I can see that it's trying to request on luislopes only... and ignores the -part

**Comment by luislopes-outsystems** [comment]
looking at the code, maybe this regex? 

`const pattern = /(?<protocol>https?:\/\/)?(?<host>gist\.github\.com\/)?((?<username>\w+)\/)?(?<gistID>\w+)(\#(?<filename>.+))?/`

**Comment by linjunpop** [comment]
OK, let me fix this.
