### ISSUE TITLE
Could not fetch the Gist from GitHub server.

### ISSUE THREAD

**Issue by jamtur01** [linjunpop/obsidian-gist#8]
Obsidian: Version 1.5.3 (Installer 1.4.16)
Gist version: 0.9.1

I see this for any gist I try and import:

```
Failed to load the Gist (GrahamcOfBorg/0e5ecdfa7b129874f745da58489fca58).

Error:

  Could not fetch the Gist from GitHub server. (Error: TypeError: Failed to fetch)
```

**Comment by yeongu-dev** [comment]
@linjunpop When can I expect the feature to be released with the issue resolved?

**Comment by linjunpop** [comment]
@yeongu-dev  0.10.0 released with another fix for the stylesheet. It should work again.
